In progress
Gubarevdll/autoSchool pull request #6
Opened 2020-12-26 13:51 UTC by Gubarevdll

Module 3 is ready for review

2020-12-29 13:53 UTC, Zetmask requested changes

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/Main.java
> +    public static Figure[] create10RandomObjects() {
Желательно не делать таких узконаправленных методов. Лучше сделать метод, который генерирует рандомную фигуру, а потом в цикле заполнить массив столько раз, сколько требуется

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/figure/Circle.java
> +        setSpace(1);
Это странно выглядит и для чего оно?

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/figure/Circle.java
> +        super.setSpace(space);
Я бы предложил сделать отдельный абстрактный метод public abstract int evaluateArea(); в Figure, а потом его оверрайдить и считать площадь для каждой фигуры. И просто вызывать setSpace(evaluateArea());

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/figure/Circle.java
> +        int b_y = (a_y + 1) + random.nextInt(10 + 1);
Лучше избегать таких повторов. Если надо генерировать рандомное число, создай метод в Main и передавай его одним из параметров при создании фигуры, а внутри класса с фигурой используй это число.
Что-то, вроде такого

new Triangle(i, randomSize());

    private static int randomSize() {
        return (int) Math.round(Math.random() * 100 + 1);
    }

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/figure/Circle.java
> +        System.out.println(getName() + " radius = " + cords[4]);
Всё-таки, такие конструкции плохо читаются (cords[2]). Тут прям и просится Map и по ключу доставать значение. Но мапы будут дальше по обучению ))

2020-12-29 13:53 UTC, Zetmask commented on src/main/java/module3/figure/Figure.java
> +    public Figure() {
а его можно уже смело удалять )

2020-12-29 14:21 UTC, Zetmask commented on src/main/java/module3/figure/Circle.java
> +        System.out.println(getName() + " radius = " + cords[4]);
Это можно не исправлять ))

2021-01-02 16:25 UTC, Gubarevdll commented on src/main/java/module3/figure/Figure.java
> +    public Figure() {
удалено

2021-01-02 16:26 UTC, Gubarevdll commented on src/main/java/module3/Main.java
> +    public static Figure[] create10RandomObjects() {
Изменил. Добавил метод для создания рандомной фигуры, который вызывается циклом в Main.

2021-01-04 08:45 UTC, Gubarevdll commented on src/main/java/module3/figure/Circle.java
> +        super.setSpace(space);
Добавил абстрактный evaluateSpaсe(); и оверрайды в каждой фигуре.

2021-01-04 10:58 UTC, Gubarevdll commented on src/main/java/module3/figure/Circle.java
> +        setSpace(1);
Это я так немного костыльно задавал координаты и площадь. 

Теперь это выполняют другие методы, как в рекомендации в комментарии ниже.

2021-01-04 11:00 UTC, Gubarevdll commented on src/main/java/module3/figure/Circle.java
> +        int b_y = (a_y + 1) + random.nextInt(10 + 1);
Добавил метод randomSize() и теперь он передает рандом в фигуры через конструктор. ###

2021-01-04 16:00 UTC, Zetmask approved these changes

2021-01-04 16:47 UTC, closed without merging